name: unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-9, g++-10, g++-11, clang++-9, clang++-10, clang++-11, clang++-12, clang++-13, clang++-14]
        build: [Release, Debug]
    env:
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        chmod +x .github/workflows/install_deps_ci.sh
        ./.github/workflows/install_deps_ci.sh
    
    - name: Install Gtest
      run: |
        chmod +x .github/workflows/install_gtest.sh
        ./.github/workflows/install_gtest.sh
    - name: run cmake
      run: |
        mkdir build && cd build
        cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
    - name: build
      run: |
        cd build
        make -j$(nproc)
    - name: run tests
      run: ./build/Test/Tests --gtest_color=yes
